#!/usr/bin/env bash
set -o errexit -o pipefail -o noclobber 

NMAE=''
while getopts ":d:s:c:n:m:h" opt; do
    case "$opt" in
        d)
            DIR="$OPTARG"
            ;;
        s)
            REF="$OPTARG"
            ;;
        c)
            COPY="$OPTARG"
            ;;
        n)
            SESSION_NAME="$OPTARG"
            ;;
        m)
            CMD="$OPTARG"
            ;;
        h)
            echo "Usage: $0 [ -d DIR ] -s SOURCE  -n SESSION_NAME [ -c copy ] [ -m CMD ]
                         $0 [-d|--dir] -n|--name [-m CMD ]"
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1;;
        --)
            break
            ;;
        :)
            echo "Option: -$OPTARG requires an argument" >&2
            exit 1;;
        esac
done

# ==================END================================
cd "$DIR"
if [[ -z $SESSION_NAME ]];
then
    echo "You must specify a session-name with -n!"
    exit 2;
fi

tmux new-session -s "$SESSION_NAME" -n main -d
if [[ -z $REF ]];
then
    tmux splitw -t 1 -d -h -p 38
else
    #tmux splitw -t 2 -d -p 30
    #tmux send-key -t 1 'nvim  -S ~/.vim/sessions/cs231n.vim' 'Enter'
    if [[ ! -r $REF ]];
    then
        echo "$REF" doesn\'t exis
        exit 3
    fi

    if [[ -z $COPY ]];
    then
        VIMCMD="nvim \"$REF\""
    else
        VIMCMD="nvim -O \"$REF\" \"$COPY\""
    fi
    tmux splitw -t 1 -d -h -p 29
    tmux send-key -t $SESSION_NAME:1.1 "$VIMCMD" 'Enter'
    tmux send-key -t $SESSION_NAME:1.2 "$CMD" '' 'Enter' 
fi
tmux rename-window -t $SESSION_NAME:1 'main'
tmux attach -t "$SESSION_NAME"
