#!/usr/bin/env python3 
# -*- coding: utf-8 -*-
import os
import requests as req
import yaml
import shutil

# url_xair='https://sub.api.cn.xeotd.cn:666/v2sub/9B7NyAd4SgVg?clash=1'
url_xair='https://api.icp-system.hwsdn.com:666/v2sub/9B7NyAd4SgVg?clash=1'

wdir=os.path.expanduser("~/.config/clash")
os.chdir(wdir)

r = req.get(url_xair, stream=True)
if r.status_code == 200:
    with open("xair.yaml",'wb') as xf:
        r.raw.decode_content = True
        shutil.copyfileobj(r.raw, xf)
print("download xair.yaml OK!")


with open("xair.yaml", 'r') as xf:
    data_x = yaml.load(xf, Loader=yaml.FullLoader)

data_x.update({'socks-port':7891})
data_x.update({'port':7890})
data_x.update({'redir-port':7892})
data_x['log-level']='info'
data_x['mode']="Rule"

for i in data_x['proxy-groups']:
    if i['name'] == 'UrlTest':
        for j in i['proxies']:
            if '回国' in j or '免费' in j  or '基础'  in j:
                i['proxies'].remove(j)

with open('config.yaml', 'w') as xair_asn:
    yaml.dump(data_x, xair_asn, allow_unicode=True)
# with open('/root/.config/clash/config.yaml', 'w') as xair_asn:
#     yaml.dump(data_x, xair_asn, allow_unicode=True)
print("update config.yaml")

rest_url = "http://127.0.0.1:9090/configs"
payload = {"path": wdir+'/config.yaml'}
r = req.put(rest_url, json=payload)
if r.status_code == 200:
    print("config reload OK!")
