#!/bin/bash
if [[ -e ./.sync || -h ./.sync || -e ./.sync.sh ]]; then
    echo "It seems that you have another .sync in this folder. Delete it first"
else
    cp ~/kit/vim-sync-sftp ./.sync
    sed -in -e s/login_name@1.2.3.4/$1/g -e  s/login_password/$2/g  -e s/remote_path/$3/g .sync
    cat .sync
fi
