#!/bin/bash -
set -o nounset                              # Treat unset variables as an error


if [[ $(file "$1") =~ "DjVu" ]]; then
    ocr.py 'djvu'
    djvused "$1" -e "set-outline tmp" -s
else
    # ocr_generate content > tmp.awk
    # chmod +x tmp.awk
    # ./tmp.awk result.txt > tmp
    # ocr_final.sh "$1"
    #-------------------------------
    ocr.py 'pdf'

    name=${1%.*}
    pdftk "$1" dump_data output "$name".info
    awk -i inplace "!/Bookmark/" "$name".info # delete old bookmarks

    # append tmp.bm generated by `ocr.py` to the line `NumberOf ...` of the metadata file of pdf
    ed -s  "${name}".info <<EOF
H
/NumberOf/-r tmp.bm
w tmp.info
q
EOF
    mv tmp.info "${name^^}".info
    pdftk "$1" update_info "${name^^}".info output "${name^^}".pdf
    rm "${name}".pdf
    mv "${name^^}".pdf "${name}".pdf
fi

# rm *.info content tmp* *.png *.txt -f 2> /dev/null

cp "$1" "/mnt/data/OneDrive - Ixsay/Libray/Front/galileo/BooksWithContentsByOCR"
