#!/bin/bash -

CURT=$(dirname $(readlink  $0))
ROOT=$(readlink  $(dirname "$CURT"))

set -o nounset                              # Treat unset variables as an error
#upper case argument
mode=$(echo "$1" | tr '/A-Z/' '/a-z/' )
if [[ $mode == 'antigen' || -z $mode ]];
then
    if [[ ! -e ~/.antigen.zsh ]];
    then
        curl -L git.io/antigen > ~/.antigen.zsh
    fi
    if [[ -e ~/.zshrc ]];
    then
        rm ~/.zshrc 
    fi
    ln -s $ROOT/zsh/zshrc_antigen ~/.zshrc
else
    if [[ -e ~/.zshrc ]];
    then
        rm ~/.zshrc 
    fi
    ln -s $ROOT/zsh/zshrc ~/.zshrc
fi
