# Path to your oh-my-zsh installation.
  export ZSH=/home/carl/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

#-------------------------------------------- host
case "$(hostname)" in
    "dream")
        alias anaconda='export PATH="/opt/anaconda/bin:$PATH"'
        ZSH_THEME="rkj-repos"
        ;;
    "elementary")
        ZSH_THEME="frisk"
        alias anaconda='export "PATH=/home/carl/anaconda3/bin:$PATH"'
        function ml(){
            if [ -n "$1" ] && [ "$1" = "exit" ];then
                cd ~
                export PS1="$PS_"
            else
                if [ -z "$(ls -A ~/wdh)" ]; then
                    echo "Trying"
                    if [ ! $(sudo mount /home/carl/wdh) ]; then
                        echo "OK"
                    else
                        echo "......"
                    fi
                else
                    cd ~/wdh/ml/
                    export PS1="%{$fg[yellow]%}(WDH_ml) $PS1"
                fi
            fi
        }
        alias cdy=' cd /mnt/share/racoon && pwd=${PWD} && sudo caddy -conf /usr/local/caddy/Caddyfile &; cd "$pwd" '
        alias cby='sudo calibre-server /mnt/share/racoon/Calibre_Library --userdb /home/carl/.config/calibre/user.sqlite --enable-auth &'
        alias jpy='sudo mount ~/wdh ; anaconda && jupyter notebook &'
        ;;
    "WDH")
        alias anaconda='export "PATH=/mnt/e/.anaconda3/bin:$PATH"'
        alias host='sudo ~/kit/update_hosts.sh'
        export set  home='/mnt/c/Users/Administrator'
        alias CD="cd $home"
        ZSH_THEME="ys"
        function ssho(){
            ssh $(nmblookup ${1} | awk '{print $1}')
        }
        ;;
    "nuages")
        ZSH_THEME="af-magic"
        ;;
    *)
        ZSH_THEME="bureau"
esac    
#--------------------------------------------

# ------------------BEGIN-----------------------
# os-specific 

os=$(cat /etc/os-release | grep '^ID=' | cut -c4- | tr '[:upper:]' '[:lower:]')
if [ -n "$os" ];then
    case "$os" in
        "arch")
            alias syslog='sudo journalctl -r'
            alias logmonitor='sudo journalctl -f'
            ;;
        "ubuntu"|"elementary")
            alias syslog='sudo less /var/log/syslog'
            alias logmonitor='sudo tail -f /var/log/syslog'
            ;;
        *)
            ;;
    esac
fi
# ==================END=========================

#ZSH_THEME="rkj-repos"
# Uncomment the frandom" line to use case-sensitive completion.
    # CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
    # sensitive completion must be off. _ and - will be interchangeable.
    # HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
    # COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
    # under VCS as dirty. This makes repository status check for large repositories
        # much, much faster.
        # DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
    # stamp shown in the history command output.
    # The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
    # HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git heroku archlinux autojump)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
#export LANG=en_US.UTF-8
#export LANG=zh_CN.UTF-8
#export LANGUAGE=zh_CN:en_US
#export LC_CTYPE=en_US.UTF-8



# Preferred editor for local and remote sessions
    # if [[ -n $SSH_CONNECTION ]]; then
        # export EDITOR='vim'
        # else
            #   export EDITOR='mvim'
            # fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
    #
    # Example aliases
    # alias zshconfig="mate ~/.zshrc"
    # alias ohmyzsh="mate ~/.oh-my-zsh"

#zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
        LESS_TERMCAP_md=$'\E[01;38;5;74m' \
        LESS_TERMCAP_me=$'\E[0m' \
        LESS_TERMCAP_se=$'\E[0m' \
        LESS_TERMCAP_so=$'\E[38;5;246m' \
        LESS_TERMCAP_ue=$'\E[0m' \
        LESS_TERMCAP_us=$'\E[04;38;5;146m' \
        man "$@"
    }

source $HOME/kit/tools.sh
export PATH="/home/carl/kit/ocr:/home/carl/kit:$PATH"


export EDITOR="nvim"
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
#export QT_IM_MODULE=ibus
#export PATH="/home/carl/algs4/bin:$PATH"

#ibus-daemon -drx

setopt extended_glob
function showme()
{
    vim "$(which $1)" 
}
function swap()         
{
    local TMPFILE=tmp.$$
    mv "$1" $TMPFILE
    mv "$2" "$1"
    mv $TMPFILE "$2"
}
#function to set or unset proxy in terminal
function setproxy() {
    export {http,https,ftp}_proxy="${1-socks5}://127.0.0.1:1080"
}
function unsetproxy() {
    unset {http,https,ftp}_proxy
}
function help() {
    bash -c "help $1"
}

plugins+=(fasd)
eval "$(fasd --init auto)"

export R_ENVIRON_USER='/home/carl/.config/r/.Renviron'


export AURDEST='/var/cache/pacaur/pkg'

#transfer.sh, to upload file and share with a link
transfer() { if [ $# -eq 0 ]; then echo -e "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md"; return 1; fi 
tmpfile=$( mktemp -t transferXXX ); if tty -s; then basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g'); curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile; else curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile ; fi; cat $tmpfile; rm -f $tmpfile; } 


#source /home/carl/kit/env_proxy
plugins+=(zsh-proxychains-ng)

#ssh log in to server hosted on vultr 
export set github="https://github.com/"

#save $PS1 for restore
export PS_="$PS1"
alias ssl="nohup  sslocal -s  144.202.105.34 -p 9525 -k vultr@_2018 &"
alias locat="locate -Abi"
alias pcs=proxychains4


alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
alias vv='fasd -e vim'

alias ev='evince '
alias wget_all='wget -r -np -k' #download all files in a page 
alias lld='ls -d */'
alias git-root='cd $(git rev-parse --show-toplevel)'
alias ucap='setxkbmap -option caps:ctrl_modifier'
alias recap='setxkbmap -option'
alias pacsort='pacsize| sort -rhk 2| less'
alias weixin='google-chrome-stable -app=https://wx.qq.com'
alias tianyi="google-chrome-stable -app=https://cloud.189.cn/main.action"
alias baiduyun="google-chrome-stable -app=https://pan.baidu.com"
alias bdpcs="baidupcs-go"
alias rsynccl='rsync -rv --delete /home/carl/mounts/galileo/main/  /home/carl/mounts/RACOON/Calibre_Library'
# alias cl2gd="rclone sync ~/mounts/galileo/Calibre_Library gd_alves:library -v --no-update-modtime"
alias mypublicip='drill +short myip.opendns.com @resolver1.opendns.com | grep IN | tac | cut -f5 -s'
alias git-root='cd $(git rev-parse --show-toplevel)'
alias du1='du -hd0'
alias ,e='nvim ~/.zshrc'
alias prm=". ~/kit/prm.sh"
alias ssh='autossh'
alias exp='less ~/kit/experience.sh'
alias exp-add='nvim ~/kit/experience.sh'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# HSTR configuration - add this to ~/.bashrc
# alias hh=hstr                    # hh to be alias for hstr
# export HISTFILE=~/.zsh_history  # ensure history file visibility
# export HSTR_CONFIG=hicolor        # get more colors
# bindkey -s "\C-r" "\eqhstr\n"     # bind hstr to Ctrl-r (for Vi mode check doc)

bindkey -e
## ------------------BEGIN------------------------------
##  ==> vi mode
#bindkey -v

## Vi mode settings
## # Better searching in command mode
#bindkey -M vicmd '?' history-incremental-search-backward
#bindkey -M vicmd '/' history-incremental-search-forward
##
## # Beginning search with arrow keys
#bindkey "^p"A up-line-or-beginning-search
#bindkey "^n" down-line-or-beginning-search
#bindkey -M vicmd "k" up-line-or-beginning-search
#bindkey -M vicmd "j" down-line-or-beginning-search
##
## # Easier, more vim-like editor opening
## # `v` is already mapped to visual mode, so we need to use a different key to
## # open Vim
#bindkey -M vicmd "^V" edit-command-line
##
## # Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
#export KEYTIMEOUT=1
## ==================END================================

# ------------------BEGIN------------------------------
#  ==> ENV VAR
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"


# Save all history
# # Incrementally write history to file
setopt INC_APPEND_HISTORY
# # Save timestamp to history file too
setopt EXTENDED_HISTORY
# # Import newly written commands from the history file
setopt SHARE_HISTORY

# ==================END================================
